In [1]:
my_dict = {"x": 10, "y": 3}
result = my_dict["x"] ** my_dict["y"]
print("x raised to the power of y is:", result)

x raised to the power of y is: 1000

In [2]:
x = 5
y = 2
if x > y:
    result = x + y
    print("The sum of x and y is:", result)
else:
    result = x - y
    print("The difference between x and y is:", result)

The sum of x and y is: 7

In [3]:
my_dict = {"name": "John", "age": 25}
name = str(my_dict["name"])
age = int(my_dict["age"])
print("My name is", name, "and I am", age, "years old.")

My name is John and I am 25 years old.

In [4]:
set1 = {1, 2, 3}
set2 = {2, 3, 4}
if 1 in set1 and 4 not in set2:
    print("Set1 contains 1 and Set2 does not contain 4.")
else:
    print("Conditions not met.")

Conditions not met.

In [5]:
tuple1 = (5, 10)
tuple2 = (7, 3)
if tuple1[0] > tuple2[0] or tuple1[1] < tuple2[1]:
    print("At least one condition is True.")
else:
    print("Both conditions are False.")

Both conditions are False.